export const t = {
  // HEADER_TEXT: "The bridge to the future of capital markets.",
  HEADER_TEXT: "",
  EMAIL: "Email",
  EMAIL_LABEL: "Ingresa email...",
  REQUIRED_EMAIL: "Email requerido",
  PASSWORD: "Contraseña",
  PASSWORD_LABEL: "Contraseña...",
  REQUIRED_PASSWORD: "Contraseña requerida",
  SIGN_IN_BUTTON: "Ingresar",
  LOADING_LOGIN: "Autenticando ...",
  FORGOT_LINK: "Recuperar contraseña",
  REGISTER_LINK: "Registro ",
  REGISTER: "Registrarse",
};
